### ISSUE TITLE
Redesign of emails 

### ISSUE THREAD

**Issue by kaskranenburgQ** [quintel/etengine#1412] opened 2024-03-29 09:21 UTC
At the moment, the design of the mails we sent to new users is in such a bad state that google automatically puts it in the spam folder, see an example below:

<img width="505" alt="Screenshot 2024-03-29 at 10 13 12" src="https://github.com/quintel/etengine/assets/150331345/24ed319a-9b4c-4a53-acf7-a822c93887de">

In the Multi user scenario support project we shortly experimented with some new designs for emails. 
The result is already an improvement to our standard design:
![Screenshot 2024-03-29 at 10 16 17](https://github.com/quintel/etengine/assets/150331345/5b51ad70-1ce3-46b6-be36-9dda893ec3a6)

The aim of this issue is to create a new "house style" for our automatically generated emails and implement this on our current set of mails. 

Quickly spoke to @noracato, she thinks a junior developer could pick this up. 
Assigning this to her for now, re-assign at will.

**Comment by mabijkerk** [comment] 2024-05-30 14:14
@noracato can we assign this to @louispt1?

**Comment by noracato** [comment] 2024-06-06 08:14
Yes! I'll reassign!

The past weeks at least three of our confirmation emails have not made it through to our users. The look and layout of this email could be the perpetrator. Would be great to pick this issue up soon, because users are contacting us a bit too much about this issue!

**Comment by noracato** [comment] 2024-06-06 08:28
Let's also check from which address the mails are sent, and make sure they all come from an `@energytransitionmodel` type address. Maybe we have to create a `noreply@energytransitionmodel.com` for example.

**Comment by noracato** [comment] 2024-06-06 13:21
Also on this note, can we add a button in the users index view for each user for whom `user.confirmed?` is false, that triggers the (re)sending of the confirmation email? `user.send_confirmation_instructions`

Will save a lot of time, because currently I have to log in to the server and manually trigger this action from Rails itself.

**Closed** 2024-06-10 09:06 UTC
