### ISSUE TITLE
A copy of Qernel::Lifecycle has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by grdw** [quintel/etengine#812] opened 2016-01-18 15:04 UTC
On development this issue arrises when editing the code and perform two of the same gqueries in a row.

Does lifecycle refere to a literal 'code' lifecycle or? 

Fyi: I don't use powder but the regular rails server.

**Comment by antw** [comment] 2016-01-18 15:36
This is basically the same as #809; objects are persisting in memory for some reason and not being reloaded correctly by Rails when editing a file.

> Does lifecycle refere to a literal 'code' lifecycle or?

It's used to manage the calculation of the graph; in particular, it allows us to change the way some things are calculated by injecting "plugins" into the calculation process. For example, [in the case of the Merit plugin](https://github.com/quintel/etengine/blob/d67fef8bfaa001abde8ad51facf71233e00eb307/app/models/qernel/plugins/merit_order.rb#L34), we can force the graph to be recalculated after the plugin has run. 

I'll close this since the problem is [well described](https://github.com/quintel/etengine/issues/809#issuecomment-172476677) by #809 already.

**Closed by antw** 2016-01-18 15:36 UTC
Labels: Bug

**Comment by antw** [comment] 2016-01-18 15:47
For what it's worth, this was never a problem with Rails 3, and only started after upgrading to v4. Maybe it would be worth trying the Rails 5 beta to see if the situation has improved?
