### ISSUE TITLE
[Airbrake] [Production] (eval):1: syntax error, unexpected '<', expecting ']' [<Converter buildings_cooling_c...   ^ (eval):1: syntax error, unexpected ',' ...mp_water_water_ts_electricity>, <Converter buildings_cooling... ...                          ...

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#845] opened 2016-06-01 07:49 UTC
**Airbrake error:** [#5780](https://quintel.airbrake.io/projects/32233/groups/1698386224787395780)
**Airbrake project:** ETE

**Error type:** `SyntaxError`
**Error message:** `` (eval):1: syntax error, unexpected '<', expecting ']' [<Converter buildings_cooling_c...   ^ (eval):1: syntax error, unexpected ',' ...mp_water_water_ts_electricity>, <Converter buildings_cooling... ...                               ^ (eval):1: syntax error, unexpected ',' ...eatpump_air_water_network_gas>, <Converter buildings_cooling... ...                               ^ (eval):1: syntax error, unexpected ',' ...g_airconditioning_electricity>, <Converter buildings_space_h... ...               ``
**Where:** `data/gqueries#test`
**Occurred at:** Jun 01, 2016 07:49:03 UTC
**First seen at:** Jun 01, 2016 07:49:03 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://engine.energytransitionmodel.com/data/latest/gqueries/test](https://engine.energytransitionmodel.com/data/latest/gqueries/test)
**File:** `[PROJECT_ROOT]/app/models/debug_table.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/debug_table.rb:38:in instance_eval
[PROJECT_ROOT]/app/models/debug_table.rb:38:in block (2 levels) in data
[PROJECT_ROOT]/app/models/debug_table.rb:32:in map
[PROJECT_ROOT]/app/models/debug_table.rb:32:in block in data
```

**Comment by jorisberkhout** [comment] 2016-06-01 09:17
This was caused by me trying the following Gquery
`TXT_TABLE(G(cost_traditional_heat), G(cost_heat_pumps), key)`

where I should have done 😖 
`TXT_TABLE(G(cost_traditional_heat, cost_heat_pumps), key)`

Closing.

**Closed by jorisberkhout** 2016-06-01 09:17 UTC
Labels: airbrake
