### ISSUE TITLE
[Airbrake] [Production] Could not find a dataset with the key "be"

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etengine#870] opened 2016-09-15 09:20 UTC
**Airbrake error:** [#4811](https://quintel.airbrake.io/projects/32233/groups/1775257780087594811)
**Airbrake project:** ETE

**Error type:** `Atlas::DocumentNotFoundError`
**Error message:** `` Could not find a dataset with the key "be" ``
**Where:** `api/v3/areas#show`
**Occurred at:** Sep 15, 2016 09:20:17 UTC
**First seen at:** Sep 15, 2016 09:20:17 UTC
**Occurrences:** 1 (0 since last deploy on `<no information>`)

**URL:** [https://engine.energytransitionmodel.com/api/v3/areas/be](https://engine.energytransitionmodel.com/api/v3/areas/be)
**File:** `[GEM_ROOT]/bundler/gems/atlas-ce45457b7ec5/lib/atlas/active_document/finders.rb`

**Backtrace:**
```
[GEM_ROOT]/bundler/gems/atlas-ce45457b7ec5/lib/atlas/active_document/finders.rb:38:in find
[PROJECT_ROOT]/app/models/etsource/loader.rb:49:in area_attributes
[PROJECT_ROOT]/app/models/area.rb:3:in get
[PROJECT_ROOT]/app/controllers/api/v3/areas_controller.rb:22:in show
```

**Comment by jorisberkhout** [comment] 2016-09-15 12:39
Hmm, I wonder why this error keeps happening. I will put a first iteration of the Belgian dataset that I'm making on the Beta server.

**Comment by jorisberkhout** [comment] 2016-09-15 12:40
Closing this as it is a duplicate of #856.

**Closed by jorisberkhout** 2016-09-15 12:40 UTC
Labels: airbrake
